package cz.ackee.cookbook.utils

import android.annotation.SuppressLint
import android.content.Context
import android.content.SharedPreferences
import android.provider.Settings.Secure
import java.util.UUID

/**
 * Factory for generating device uuid
 *
 * Borrowed from StackOverflow answer http://stackoverflow.com/a/5628136/1478296
 */
@SuppressLint("HardwareIds")
class DeviceUuidFactory(private val context: Context, private val prefs: SharedPreferences) {

    companion object {
        private val PREFS_DEVICE_ID = "device_id"
    }

    /**
     * Returns a unique UUID for the current android device. As with all UUIDs,
     * this unique ID is "very highly likely" to be unique across all Android
     * devices.
     *
     *
     * The UUID is generated by using ANDROID_ID as the base key.
     *
     *
     * In some rare circumstances, this ID may change. In particular, if the
     * device is factory reset a new device ID may be generated. In addition, if
     * a user upgrades their phone from certain buggy implementations of Android
     * 2.2 to a newer, non-buggy version of Android, the device ID may change.
     * Or, if a user uninstalls your app on a device that has neither a proper
     * Android ID nor a Device ID, this ID may change on reinstallation.
     *
     * @return a UUID that may be used to uniquely identify your device for most purposes.
     */
    val deviceUuid: UUID
        get() {
            synchronized(DeviceUuidFactory::class.java) {
                val id = prefs.getString(PREFS_DEVICE_ID, null)
                return if (id != null) {
                    // Use the ids previously computed and stored in the prefs file
                    UUID.fromString(id)
                } else {
                    val androidId = Secure.getString(context.contentResolver, Secure.ANDROID_ID)
                    val uuid = UUID.nameUUIDFromBytes(androidId
                            .toByteArray(charset("utf8")))
                    // Write the value out to the prefs file
                    prefs.edit().putString(PREFS_DEVICE_ID, uuid.toString()).apply()
                    uuid
                }
            }
        }
}